@extends('landing.layouts.app')

@section('content')
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
    <h1>ashdkj</h1>
@endsection
